### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fffrog** [cosdt/torch_npu#1]
# roadmap

- [ ] Stream、Event  -> zhenbin-8
- [ ] PyTyte -> zhenbin-8
- [ ] Allocator -> zhenbin-8
- [ ] Device、DeviceGuard -> shink
- [ ] CI -> shink
- [ ] doc preview -> shink
- [ ] MACROS、Exception -> zong
- [ ] Generator、lazy_init -> zong
- [ ] generate_code.sh -> fffrog
- [ ] codegen -> fffrog

- [ ] cmake refactor
- [ ] NPUCachingHostAllocator.h
- [ ] Move headers and libs into correct directory when installed.
