### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fffrog** [cosdt/torch_npu#34]
- [ ] [元昊] autoload torch.npu & torch_npu.npu
- [x] [元昊] NPUGuardImpl.cpp 内部注册拆分 #47 
- [x] [元昊] DeviceProp 下移到 csrc/npu下（可以参考XPU实现）
- [x] [元昊] AclInterface.h 删除 #46 
- [x] [元昊] 新增 torch_backend._C 的 pyi文件（代码提示）#79
- [ ] [逢春] StreamGuard.h 按需重构
- [ ] [逢春] HasCompatibleShallowCopyType.cpp Warning定位（这个可以改成设备无关，不通过dispatcher调用）
- [x] [逢春] Refactor AutocastMode.cpp（官方提供了默认列表，对比差异，如果一样可以直接调用宏）
- [x] [逢春] npu init & finalize 重构
- [x] [泽升] torch_npu/optim 删除
- [x] [泽升] testing删除以及新的test framework
- [ ] [泽升] namespace 设计
- [x] [贞斌] NPUPluggableAllocator.h删除
- [x] [贞斌] torch_npu/csrc/Module.cpp 单独拆出来内存相关
- [ ] [贞斌] NPU LOG重新设计，ERROR打印错误栈
- [x] [佳伟] aten 重构
- [ ] [佳伟] torch_npu/utils refactor
- [x] [佳伟] npu+op-plugin 新建仓库
- [x] [佳伟] NPUGuard.h 移到 csrc/npu
- [ ] [贞斌] autocast 设备相关api，兼容社区最新api
- [ ] [待定] deviceguard api完备度缺失，后续考虑对标CUDA（torch.Stream("npu:0")）
- [x] [泽升] REAMDE.md
- [x] [泽升] LICENSE update
- [x] [泽升] torch_npu/utils 无用代码删除
- [ ] [ALL] 文档
- [x] [贞斌] torch_npu/csrc/Module.cpp内容未拆分完全
- [ ] [待定] torch_npu/npu/utils.py内容未拆分
- [x] [逢春] maybe_initialize_npu删除，替换成device_lazy_init
- [ ] [待定] torch_npu 移除npu前缀
- [ ] [待定] _npu_is_bf16_supported 新增
- [ ] [待定] 补齐 CachingAllocator NPUCachingAllocator NPUCachingHostAllocator NPUCachingAllocatorHelper 宏 [PR](https://github.com/cosdt/torch_npu/pull/61)
- [ ] [待定] 新增 提供device name的API
